from __future__ import annotations


def handle_request(request: dict) -> dict:
    operation = request.get("operation")

    if operation == "analyze":
        payload = request["payload"]
        title = payload.get("title", "Untitled Material")
        content = payload.get("content", "")
        preview = " ".join(content.split())[:220] or "Background needs more detail."
        return {
            "ok": True,
            "payload": {
                "summary": f"MetaGPT mock completed a structured analysis for '{title}'.",
                "background": preview,
                "goals": ["Align requirement language", "Validate the local MetaGPT bridge"],
                "painPoints": ["This is a mock backend and not a real multi-agent review output yet."],
                "roles": ["Delivery consultant", "Business owner"],
                "processNotes": ["Result generated by the MetaGPT mock bridge backend."],
                "requirementCandidates": [],
                "functionCandidates": [],
                "risks": ["Install the real MetaGPT runtime before using this result for formal delivery."],
                "openQuestions": ["Switch METAGPT_BACKEND to 'metagpt' after the real runtime is installed."],
            },
            "meta": {"backend": "mock"},
        }

    if operation == "generate_document":
        payload = request["payload"]
        document_type = payload.get("documentType", "requirements_doc")
        material_title = payload.get("materialTitle", "Untitled Material")
        analysis = payload.get("analysis", {})
        summary = analysis.get("summary", "Analysis summary needs to be generated.")

        return {
            "ok": True,
            "payload": (
                f"# {material_title}\n\n"
                f"> MetaGPT mock document for `{document_type}`\n\n"
                f"## Analysis Summary\n\n{summary}\n\n"
                "## Current Status\n\n"
                "- This document was generated by the MetaGPT mock bridge backend.\n"
                "- Install and enable the real MetaGPT runtime to get multi-agent outputs.\n"
            ),
            "meta": {"backend": "mock"},
        }

    return {"ok": False, "error": f"Unsupported operation: {operation}", "meta": {"backend": "mock"}}
